Configured Launch screen and Onboarding
Leitento/mams.paps.IOs pull request #1
Opened 2023-11-24 14:40 UTC by Krostal

Configured Launch and Onboarding screens

2023-11-24 15:17 UTC, ruslangaifullin94 requested changes
Общее: добавить MARK
Если не знаешь как там с вьюМоделью разобраться, можем созвониться как нибудь, объясню, тоже самое про пейджВьюКонтроллер
Константы вынесены - хорошо
Стринги лучше сразу вынести в отдельный файл и использовать локализацию и постепенно туда добавлять, чем потом переводить весь проект
для локализации сделать расширение(скину пример в личку)
Опять же - контроллер знает только о своей модели, все делегаты и тд - в нее

2023-11-24 15:17 UTC, ruslangaifullin94 commented on mams.paps/Coordinators/OnboardingCoordinator.swift
> +    func onboardingCoordinatorDidFinish(_ coordinator: OnboardingCoordinator)
Здесь не нужно передавать конкретный тип, OnboardingCoordinator заменить CoordinatorProtocol

2023-11-24 15:17 UTC, ruslangaifullin94 commented on mams.paps/PresentationLayer/Assets.xcassets/OnboardingScreen/FirstPage.imageset/FirstPage.png
текст надо вынести из картинки, если завтра решат поменять текст, придется менять картинку, такое себе

2023-11-24 15:17 UTC, ruslangaifullin94 commented on mams.paps/PresentationLayer/OnboardingScreen/OnboardingView.swift
> +    var viewModel: OnboardingViewModel
не вижу использования viewModel в этом классе, зачем тогда инициализировать?
если надо, почему не private?

2023-11-24 15:17 UTC, ruslangaifullin94 commented on mams.paps/PresentationLayer/OnboardingScreen/OnboardingPageViewController.swift
PageViewController тут не нужен, я предлагал так:
Есть только один контроллер, на нем есть pageControl кнопка и текст между ними и вью с картинкой и текстом, которая будет меняться в зависимости от стейта(текст тоже под Стейт подстраивается)
И не будет этого перехода между контроллерами, а будет только смена вью, и. тогда будет видна анимация у пейджконтрола

2023-11-24 15:17 UTC, ruslangaifullin94 commented on mams.paps/PresentationLayer/OnboardingScreen/OnboardingViewModel.swift
Модель - класс
enum внутри этого класса с просто именем State
Все методы переходов и смены состояний внутри модели делаем
Чекать состояние модели лучше через замыкание

2023-11-24 15:17 UTC, ruslangaifullin94 commented on mams.paps/PresentationLayer/OnboardingScreen/OnboardingView.swift
> +        let statusBarHeight = window?.windowScene?.statusBarManager?.statusBarFrame.height
почему не safeArea?

2023-11-24 15:24 UTC, Krostal commented on mams.paps/PresentationLayer/OnboardingScreen/OnboardingView.swift
> +        let statusBarHeight = window?.windowScene?.statusBarManager?.statusBarFrame.height
по дизайну в фигме так, если к safeArea крепиться - сильно ниже картинка получается

2023-11-24 15:50 UTC, Krostal commented on mams.paps/Coordinators/OnboardingCoordinator.swift
> +    func onboardingCoordinatorDidFinish(_ coordinator: OnboardingCoordinator)
ок

2023-11-24 15:56 UTC, Krostal commented on mams.paps/PresentationLayer/Assets.xcassets/OnboardingScreen/FirstPage.imageset/FirstPage.png
ок, нужно в фирме попросить чтобы картинку без текста сделали

2023-11-24 16:08 UTC, Krostal commented on mams.paps/PresentationLayer/OnboardingScreen/OnboardingView.swift
> +    var viewModel: OnboardingViewModel
здесь viewModel лишняя - удалил

2023-11-27 13:02 UTC, ruslangaifullin94 reviewed
Нужно созвониться по модели и локализации)
в целом ок, подправь замечания, и добавь МАРКИ))
И структуру предлагаю раскидывать по экранам, не нужно это - presentationLayer и тд
просто onboardingScreen
MainScreen
LoginScreen и тд

2023-11-27 13:02 UTC, ruslangaifullin94 commented on mams.paps/App/SceneDelegate.swift
> +        let onboardingViewController = OnboardingViewController()
здесь должен быть координатор, в котором будем определять первый запуск приложения или нет, показывать онбординг или нет, его же не нужно при каждом запуске показывать

2023-11-27 13:02 UTC, ruslangaifullin94 commented on mams.paps/Common/UIScrollView+.swift
Название файла: UIScrollView+Extension
Но опять же, так выносим только общие экстеншены, которые будут нужны во всем проекте, тут я сомневаюсь что пригодится, поэтому сделал бы в файле контроллера и private extension

2023-11-27 13:02 UTC, ruslangaifullin94 commented on mams.paps/Coordinators/OnboardingCoordinator.swift
> +    let navigationController: UINavigationController
private

2023-11-27 13:02 UTC, ruslangaifullin94 commented on mams.paps/Coordinators/OnboardingCoordinator.swift
> +//extension OnboardingCoordinator: OnboardingViewControllerDelegate {
если закомментил, значит не надо, удаляй, не пуш такое

2023-11-27 13:02 UTC, ruslangaifullin94 commented on mams.paps/Coordinators/ProtocolCoordinator.swift
> +protocol CoordinatorProtocol: AnyObject {
координатор протокол содержит все только один метод - старт, который показывает необходимый тебе координатор, все остальное делается внутри каждого координатора или отдельным протоколом, иначе тебе придется все эти методы поддерживать в каждом координаторе, нарушаем SOLID

2023-11-27 13:02 UTC, ruslangaifullin94 commented on mams.paps/en.lproj/Localizable.strings
Ты знаешь как работает локализация?)

2023-11-27 13:02 UTC, ruslangaifullin94 commented on mams.paps/PresentationLayer/Onboarding/OnboardingViewModel.swift
> +    var StateDidChange: ((State) -> Void)?
stateDidChange - это свойство с маленькой буквы

2023-11-30 16:59 UTC, ruslangaifullin94 approved these changes
в целом ок, на след задаче правки внеси

2023-11-30 16:59 UTC, ruslangaifullin94 commented on mams.paps/App/SceneDelegate.swift
> +        mainCoordinator = MainCoordinator()
так себе способ написания, не прокатит на ревью
let mainCoordinator = MainCoordinator()
self.mainCoordinator = mainCoordinator

исправь потом

2023-11-30 16:59 UTC, ruslangaifullin94 commented on mams.paps/Onboarding/OnboardingViewModel.swift
> +struct Slide {
вынеси в отдельный файл

2023-11-30 17:00 UTC, merged